name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag starkarabil/docker-image-autobuild:latest
    - name: Push the Docker image
      run: docker login -u starkarabil -p ${{ secrets.DOCKER_TOKEN }} && docker push starkarabil/docker-image-autobuild:latest
